DROP TABLE ASYNC400.Q CASCADE CONSTRAINTS;

CREATE TABLE ASYNC400.Q
(
  Q_ID         NUMBER,
  Q_NAME       VARCHAR2(1 BYTE),
  C_DATE       DATE,
  C_TIMESTAMP  TIMESTAMP(6)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
